version: '2.1'
services:
  frictionless-docs:
    image: frictionless-docs:latest
    restart: 'no'
    volumes:
      - ./:/home/node/portal
      - ../docs:/home/node/docs
    ports:
      - "3000:3000"
    working_dir: /home/node/portal
    command: 'npm start -- --host 0.0.0.0' 
