module.exports = {
  "table-schema": [
    "table-schema/python",
    "table-schema/javascript",
    "table-schema/ruby",
    "table-schema/php",
    "table-schema/java",
    "table-schema/go",
    "table-schema/rlang",
    "table-schema/julia",
    "table-schema/swift",
    "table-schema/clojure",
  ],
  "data-package": [
    "data-package/python",
    "data-package/javascript",
    "data-package/ruby",
    "data-package/php",
    "data-package/java",
    "data-package/go",
    "data-package/rlang",
    "data-package/julia",
    "data-package/swift",
    "data-package/clojure",
  ],
  "other-libraries": [
    "other-libraries/frictionless-ckan-mapper",
    "other-libraries/data-package-pipelines",
    "other-libraries/data-package-render",
    "other-libraries/goodread",
  ],
};
